# Generated by Django 2.1.4 on 2018-12-17 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadSpeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIMESTAMP', models.DateTimeField(auto_now_add=True)),
                ('STUDENT_NAME', models.CharField(max_length=200)),
                ('SUBJECT_NAME', models.CharField(max_length=200)),
                ('TOUGHNESS_LEVEL', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=200)),
                ('TYPE_OF', models.CharField(choices=[('Theoritical', 'Theoritical'), ('Practical', 'Practical'), ('Numerical', 'Numerical'), ('Other', 'Other')], max_length=200)),
                ('SUBJECT_SYLLABUS', models.CharField(choices=[('Very Lengthy (800+ pages)', 'Very Lengthy (800+ pages)'), ('Lengthy (600+ pages)', 'Lengthy (600+ pages)'), ('Medium (400+ pages)', 'Medium (400+ pages)'), ('Short', 'Short')], max_length=200)),
                ('PREFERRED_READING', models.CharField(choices=[('Notes', 'Notes'), ('Book', 'Book'), ('Video', 'Video')], max_length=200)),
                ('INTEREST_LEVEL', models.CharField(choices=[('Very Interesting', 'Very Interesting'), ('Interesting', 'Interesting'), ('Normal', 'Normal'), ('Boring', 'Boring')], max_length=200)),
                ('SUPPORTING_KNOWLEDGE', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], max_length=200)),
                ('AVERAGE_READING', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('CURRENT_STATUS', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('NUMBER_OF', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('DUE_DATE', models.DateTimeField()),
                ('DESIRED_NUMBER', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('CHECKING_LEVEL', models.CharField(choices=[('Strict', 'Strict'), ('Normal', 'Normal'), ('Lenient', 'Lenient')], max_length=200)),
                ('MARKS_IN', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('EDUCATION_TYPE', models.CharField(choices=[('School', 'School'), ('Graduation', 'Graduation'), ('Post Graduation', 'Post Graduation')], max_length=200)),
                ('SEMESTER', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('AS_PER', models.FloatField()),
            ],
        ),
    ]
