# Generated by Django 2.1.4 on 2018-12-18 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rspeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readspeed',
            name='AS_PER',
            field=models.FloatField(verbose_name='NO OF HOURS REQUIRED AS PER YOU'),
        ),
        migrations.AlterField(
            model_name='readspeed',
            name='AVERAGE_READING',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='AVG TIME READING PER PAGE (IN MINS)'),
        ),
        migrations.AlterField(
            model_name='readspeed',
            name='CURRENT_STATUS',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='CURRENT STATUS ON SCALE OF 1 TO 10'),
        ),
        migrations.AlterField(
            model_name='readspeed',
            name='DUE_DATE',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='readspeed',
            name='EDUCATION_TYPE',
            field=models.CharField(choices=[('School', 'School'), ('Graduation', 'Graduation'), ('Post Graduation', 'Post Graduation')], default='Graduation', max_length=200),
        ),
        migrations.AlterField(
            model_name='readspeed',
            name='MARKS_IN',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='MARKS IN SIMILAR SUBJECT'),
        ),
        migrations.AlterField(
            model_name='readspeed',
            name='NUMBER_OF',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='NO OF REVISION'),
        ),
        migrations.AlterField(
            model_name='readspeed',
            name='PREFERRED_READING',
            field=models.CharField(choices=[('Notes', 'Notes'), ('Book', 'Book'), ('Video', 'Video'), ('Multiple', 'Multiple')], max_length=200),
        ),
        migrations.AlterField(
            model_name='readspeed',
            name='TYPE_OF',
            field=models.CharField(choices=[('Theoritical', 'Theoritical'), ('Practical', 'Practical'), ('Numerical', 'Numerical'), ('Other', 'Other')], max_length=200, verbose_name='TYPE OF SUBJECT'),
        ),
    ]
